server:
  port: 10000

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  better:
    websocket:
      server:
        serverPort: 10001
        childGroupThreadNumber: 1000
        parentGroupThreadNumber: 0
      connect:
        pathPrefix: /websocket
        maxContentLength: 10MB
        wsReadTimeout: 60000
        wsWriteTimeout: 60000
